#!/bin/sh

# scripts/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -ev

BUILD_TYPE=${1-Release}

cd "$(dirname "$0")/.."

BASH_PROFILE='.bash_profile'
[ -f "${BASH_PROFILE}" ] && source ${BASH_PROFILE}

echo "CI started at…"
date "+%H:%M:%S"

# Lint
echo "Linting"
date "+%H:%M:%S"
scripts/lint

# run tests
echo "Running tests…"
date "+%H:%M:%S"
scripts/test

# run cibuild.
echo "Create build"
date "+%H:%M:%S"
scripts/build ${BUILD_TYPE}

echo "Done"
date "+%H:%M:%S"
