#!/bin/sh

# scripts/lint: Run lint for application.

set -ev

cd "$(dirname "$0")/.."

BASH_PROFILE='.bash_profile'
[ -f "${BASH_PROFILE}" ] && source ${BASH_PROFILE}

[ -z "$DEBUG" ] || set -x

echo "==> Running static analysis…"

swiftlint lint --config .swiftlint --strict --quiet
