#!/bin/sh

# scripts/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -ev

cd "$(dirname "$0")/.."

BASH_PROFILE='.bash_profile'
[ -f "${BASH_PROFILE}" ] && source ${BASH_PROFILE}

scripts/bootstrap

echo "==> Setting up xcodeproj…"
swift package generate-xcodeproj

echo "==> Project is now ready to go!"
