#!/bin/sh

# scripts/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Running tests…"

MACOSX_DEPLOYMENT_TARGET=${1-'x86_64-apple-macosx10.12'}
swift test -Xswiftc "-target" -Xswiftc "${MACOSX_DEPLOYMENT_TARGET}"
