#!/bin/sh

# scripts/update: Update application to run for its current checkout.

set -ev

cd "$(dirname "$0")/.."

BASH_PROFILE='.bash_profile'
[ -f "${BASH_PROFILE}" ] && source ${BASH_PROFILE}

swift package update
scripts/setup
